steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg' , 'MONGO_URI=${{ secrets.MONGO_URI }}' , '-t', 'us-central1-docker.pkg.dev/dmeiry-7/project-repo/skitick2:latest', '.']

# Step 2: Push the Docker image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dmeiry-7/project-repo/skitick2:latest']

# Step 3: Deploy the Docker image to Google Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - --set-env
    - MONGO_URI=${{ secrets.MONGO_URI }}
    - 'deploy'
    - 'skitick2'  # Replace with your Cloud Run service name
    - '--image'
    - 'us-central1-docker.pkg.dev/dmeiry-7/project-repo/skitick2:latest'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'  # Replace with your desired region
    - '--allow-unauthenticated'  # Optional: Allows unauthenticated access; remove if not needed
images:
- 'us-central1-docker.pkg.dev/dmeiry-7/project-repo/skitick2:latest'

options:
  logging: CLOUD_LOGGING_ONLY  # Logs will be sent to Cloud Logging only